ALTER TABLE "application" DROP COLUMN "healthCheckSwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "restartPolicySwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "placementSwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "updateConfigSwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "rollbackConfigSwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "modeSwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "labelsSwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "networkSwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "stopGracePeriodSwarm";--> statement-breakpoint
ALTER TABLE "application" DROP COLUMN "endpointSpecSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "healthCheckSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "restartPolicySwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "placementSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "updateConfigSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "rollbackConfigSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "modeSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "labelsSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "networkSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "stopGracePeriodSwarm";--> statement-breakpoint
ALTER TABLE "libsql" DROP COLUMN "endpointSpecSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "healthCheckSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "restartPolicySwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "placementSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "updateConfigSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "rollbackConfigSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "modeSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "labelsSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "networkSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "stopGracePeriodSwarm";--> statement-breakpoint
ALTER TABLE "mariadb" DROP COLUMN "endpointSpecSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "healthCheckSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "restartPolicySwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "placementSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "updateConfigSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "rollbackConfigSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "modeSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "labelsSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "networkSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "stopGracePeriodSwarm";--> statement-breakpoint
ALTER TABLE "mongo" DROP COLUMN "endpointSpecSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "healthCheckSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "restartPolicySwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "placementSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "updateConfigSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "rollbackConfigSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "modeSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "labelsSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "networkSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "stopGracePeriodSwarm";--> statement-breakpoint
ALTER TABLE "mysql" DROP COLUMN "endpointSpecSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "healthCheckSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "restartPolicySwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "placementSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "updateConfigSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "rollbackConfigSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "modeSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "labelsSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "networkSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "stopGracePeriodSwarm";--> statement-breakpoint
ALTER TABLE "postgres" DROP COLUMN "endpointSpecSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "healthCheckSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "restartPolicySwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "placementSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "updateConfigSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "rollbackConfigSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "modeSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "labelsSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "networkSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "stopGracePeriodSwarm";--> statement-breakpoint
ALTER TABLE "redis" DROP COLUMN "endpointSpecSwarm";